### ISSUE TITLE
Being maintained?

### ISSUE THREAD

**Issue by russel** [adamgreig/rtlsdr-rs#6]
Is this project being maintained or is it now left by the wayside.

I am trying to choose between https://github.com/jpoirier/rust-rtlsdr, https://github.com/adamgreig/rtlsdr-rs  and https://github.com/kchmck/rtlsdr_sys.rs as a possible choice for a Rust rewrite of some C code that uses librtlsdr.

**Comment by adamgreig** [comment]
Hey @russel,

I'm not actively doing any development work but I've not abandoned the project, it still builds on rust stable and I expect to keep it that way. I think it's more or less feature complete, though documentation is entirely lacking and I don't have any immediate plans to write any. Pull requests are accepted if you find something you need is lacking ;)

**Comment by russel** [comment]
@adamgreig Thanks for replying. Good to know things are still maintained if not actively active.

**Comment by russel** [comment]
@adamgreig Is this a wrapper for the actively maintained https://github.com/librtlsdr/librtlsdr or for the seemingly dormant  http://cgit.osmocom.org/rtl-sdr/ ?

**Comment by adamgreig** [comment]
It was written against the osmocom library, but the actively maintained one is backwards compatible / a fork, so whichever gets dynamically loaded on your system is the one it will use.

This rust wrapper doesn't have a binding for the `rtlsdr_set_tuner_gain_ext`, `rtlsdr_set_ds_mode`, `rtlsdr_ir_query`, or `rtlsdr_set_bias_tee` functions from the new librtlsdr (yet!) though they wouldn't be hard to add, just it would break compatibility with the common osmocom library. As I understand it they're all a bit more niche.
